### ISSUE TITLE
Fractional Load limits <1

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#10]
Currently, Load is rounded when it is fetched from the db, so it's either 0 or more than 0.04. Limit utilization report rounds it again.

I set a Load limit of 0.04 (1/25) for a deck.
When Load is rounded to ≥1, the add-on sets the limit to 0.
When Load is rounded to 0, the add-on keeps the preset's limit. Because the preset is used by all decks in the subtree, it allows more new cards than the limit of 0.04 can fit.
The "Easy" button's ivl in this preset is 25d, which creates a Load of 0.04.
I ran FSRS' reschedule after rating a card "Easy", and the interval became ⁨29⁩d, which is about 0.03448 of Load.
So, depending on the fuzz, only 1 or 2 cards should be learned when this deck's Load is 0. 

I don't know what it would take to find the probable maximum "Easy" interval, but that probably doesn't matter, because the user will likely fail a card soon enough to make Load at least 1. At least I am trying to use this to balance many decks that are not very important (this makes everything in the deck list slower).

```python3
        if 0 < newLimit < 1.0:
            newLimit = 1
        else:
            newLimit = round(newLimit)
```

**Comment by aleksejrs** [comment]
```python3
        newLimit = max(0, min(maxNewCardsPerDay - introduced_today, youngCardLimit - youngCount, round(loadLimit - load))) + introduced_today
```

round(loadLimit - load)

0.04 - 0 = 0.04, rounded to 0 → no new cards ever?

**Comment by lune-stone** [comment]
Good catch. There probably isn't any strong reason to use `round()` with 0.5 as the cutoff here.
