### ISSUE TITLE
Indicate that a deck is empty or has no new cards in reports

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#13]
Sometimes I look at the report to see which deck's load is least utilized, so I can custom learn a card from it.
But some of the decks at the bottom are empty, so it doesn't matter what the utilization or limit is.
Maybe the report could say something like
`0.00% (0.00 of 210.0, empty)	Default`
or
`empty (0.00 of 210.0)	Default`
or
`0.00% ((empty deck) of 210.0)	Default`

Other decks that contain no non-suspended new cards should also be marked.
`0.00% (0.00 of 210.0, no new cards)	Default`

Also decks that contain only new cards could be marked, because, in addition to having the lowest possible load of any kind, they also haven't been started yet.

**Comment by lune-stone** [comment]
I've also noticed myself mentally trying to filter out decks that are either completed or not started, where the number of new cards allowed doesn't matter as much.

There are probably a few ways of dealing with this:

- adding labels
- sectioning / sub dividing
- interactive ui controls to filter

There are also some other cleanups for both code and rendering I've been considering as well. 

I've have to think a bit more on this one before I decide which direction I want to go, and how much to change I want to do in "one bite".

**Comment by aleksejrs** [comment]
I just have to mention that "0.00% (x of ∞)" are not sorted considering `(1000 of ∞) > (1 of ∞)`.
Same with `(0 of 1) > (0 of 1000)`.
Though it is good that they are sorted according to the rulesets or something then.

**Comment by aleksejrs** [comment]
I find it confusing that decks can have `of ∞` in some sections of the utilization report while they have limits in others. I expected somehow that the other rules matching the decks would apply the missing limits.

**Comment by aleksejrs** [comment]
Awesome!
