### ISSUE TITLE
limit new by in progress

### ISSUE THREAD

**Issue by Ficello** [lune-stone/anki-addon-limit-new-by-young#18]
Hello, is it possible to set the addon so that it goes from 0 new to 1 new depending on my number of cards in progress so that I maintain a good workflow. (So I always have a new card in learning but never more than 2 in order to continue moving forward on my delay)
Thx !

**Comment by lune-stone** [comment]
Just for clarity, does "in progress" refer to a specific measurement or card state?

If "in progress" is used in the general way to refer to cards that haven't yet reached maturity then yes. You can use Anki's `Deck > Options > Daily Limits > New cards/day` to set the max new cards you want in a day (1), then using add-on's `youngCardLimit` you can control the total number of young (un-matured) cards allowed for the deck (2). This way each day you will get either 0 or 1 new card, and the total number of cards in that are "young" will not exceed 2 (excluding mistakes on mature cards that bring them back into the young bucket). Once you have 2 young cards no new cards will be introduced until one or both of them become mature through successful reviews.

**Comment by aleksejrs** [comment]
@lune-stone Cardistry had a "minimum" setting.

**Comment by Ficello** [comment]
Thanks for your replies !
menwide, i thinks i'm doing somthing wrong. Indeed, i set the load to a hight level so i can learn the most following my progress in the joung carts (load 200, younglimit 2 beacause i'm using image occulision so the cart are dificult and it takes times), but the limit doesn't work : they just introduce me a thrid card wild i already had two imatures cards (whose were introduced after i set up the addon)
There is my config : 
{
    "limits": [
        {
            "deckNames": [
                "PASS::stock"
            ],
            "loadLimit": 2.0,
            "youngCardLimit": 200
        }
    ],
    "rememberLastUiSettings": true,
    "showNotifications": false,
    "updateLimitsAfterSync": false,
    "updateLimitsIntervalTimeInMinutes": 15,
    "updateLimitsOnApplicationStartup": false,
    "updateLimitsOnInterval": false,
    "utilizationReport": {
        "complete": true,
        "detailLevel": "Verbose",
        "empty": true,
        "noLimit": true,
        "notStarted": true,
        "overLimit": true,
        "subDeck": true,
        "underLimit": true
    }
}

**Comment by aleksejrs** [comment]
@Ficello 
> (load 200, younglimit 2

> "loadLimit": 2.0,
> "youngCardLimit": 200

**Comment by Ficello** [comment]
we will start by that !
But it's intrigant that it does not have change the news limit, no ? (in my case i dont need new limit so its fine ahah)
Update soon wp

**Comment by aleksejrs** [comment]
@Ficello, check the items in the "Tools → Limit New by Young" menu.

@lune-stone, https://github.com/lune-stone/anki-addon-limit-new-by-young?tab=readme-ov-file#setup is not up-to-date about the menu.

**Comment by Ficello** [comment]
The new issue is : he is able to limit the load (is load<news in deck, then :  news for today< new in deck) but the youngCardLimit dosen't work : it's like he is not dynamic : he is not updating the number of aviable news  (currently i'we set it to 2, and my number of news card aviables is 0)

**Comment by lune-stone** [comment]
To refresh the limit you will want to use `Tools > Limit New by Young > Recalculate today's new card limit for all decks` each time you change the limits on a deck.

If you are still not seeing today's limit change, you might be able to use the utilization report to see what is going on. Use `Tools > Limit New by Young > Show limit utilization report` to view the report. Setting the detail level to `Verbose` will let you see what the limit and current value of "young" is for each deck.

**Comment by Ficello** [comment]
i'm currently 999999% of younglimit. Waht doest it mean ?

**Comment by aleksejrs** [comment]
> i'm currently 999999% of younglimit. Waht doest it mean ?

Please post the whole line.

**Comment by Ficello** [comment]
=== Young Limit ===

9999.99% (432 of 2)	PASS S2::stock

- I have to change the new limit myself becase it's set it self at 0 new for today (regarless that my load is at 400)

**Comment by lune-stone** [comment]
> 9999.99% (432 of 2) PASS S2::stock

This means the deck has 432 young cards at the moment.

>   Young: A young card is one that has an interval of less than 21 days, but is not in learning.
>   Mature: A mature card is one that has an interval of 21 days or greater.
https://docs.ankiweb.net/getting-started.html?highlight=young#cards

And the limit for young cards is set to 2. The utilization is calculated as `utilization = young / limit`, but we display 9999.99% for very large values (in this case the exact utilization is 21600.00%).

When the utilization is >= 100%, no new cards will be introduced. If you do not change the limit, then you will have to wait until all of the existing young cards get enough good reviews to go from young to mature (interval >= 21 days). Once the total number of young cards is less than the limit (as in 0 or 1 young cards) then new cards would start to be added again.

I suspect that having "2" as the limit is not what you want to do and you will likely want to pick a value that is higher. Think about how you are doing with the deck. Has it been easy to learn cards so far? Or has it been a struggle to keep up? If everything is going fine, then maybe a limit of 500 young would be good. If you are feeling a bit overwhelmed then maybe a limit of 400 would be good. You can always adjust again in the future if you need to.

**Comment by Ficello** [comment]
Oh wow i hadn't understood what young mean at all !
It's a very hard deck for a upcoming test. I need to learn a lot of news hard card wille i'm reviwing my old's one (those who had been learn, regarless if it's < or > of 21 days) without beeing stuck beetwin a certain number of (hard) 'in progress' card bcs i thinks that is a situation were i'm not productiv.
So my goal is that the news card show up in fonction of the number of my in progress card and there situation (6mn loop or 10) o i dont get stuck. 
Can your addon do this ?
Sry for the hard communication, english is not my language

**Comment by lune-stone** [comment]
That adds some helpful context, thanks.

To be honest this add-on may not be the best tool to use for preparing for a test. It mostly acts as a limiter to slow down how many new cards you are shown so that you are not overwhelmed, and don't have to manage/tune that yourself, but the add-on doesn't really consider or understand the concept of a deadline that an upcoming test would introduce.

Another aspect that isn't great is that if there are cards that act as a "leech", as in cards that are too hard to understand and almost always result in pushing the "again" button, those cards will stick around and take away your study time from other easier to learn cards. The add-on is even more sensitive to leeches then regular Anki is, which could result in a lower test score if you end up not learning as much material.

Put another way, the add-on works best for long term study on large multi-year decks (like learning foreign languages). Maybe it will still be helpful for your use-case, but I'm not sure that it will, sorry.

Anki's documentation does have a few recommendations for test preparation: https://faqs.ankiweb.net/settings-for-using-anki-to-prepare-for-a-large-exam.html . Beyond that my own recommendation is to use Anki's stats page to identify which cards you want to do additional study on or suspend for later as they are more difficult than other cards. This can be done by clicking on the graph bar on the "Card Difficulty" to get a list of cards.

**Comment by lune-stone** [comment]
Closing this as answered. Feel free to reopen if you have additional questions.
