### ISSUE TITLE
subdeck support

### ISSUE THREAD

**Issue by lune-stone** [lune-stone/anki-addon-limit-new-by-young#2]

**Comment by lune-stone** [comment]
From testing c948a5f it looks like `mw.col.find_cards(f'deck:"{deckIndentifer.name}" ...')` already includes cards from subdecks and `mw.col.decks.all_names_and_ids()` will apply limits to both parent and child decks.

Still need to decide if behavior is desired and if there should be a config option to only apply limits to just the parent decks.

**Comment by aleksejrs** [comment]
It could get the numbers for all the matching decks and then calculate from that, so subdecks and the superdeck can both have limits without calculating the loads twice.

Then it could be modified to base the decision about a deck on the state of other decks.
For example, the low-prio deck would get no new cards if the high-prio deck exceeded its limits, without limiting the high-prio deck because of a backlog in the low-prio deck.
IOW, if the high-prio deck exceeded its limits, the low-prio deck will get no cards. My high-prio decks are inside my low-prio decks (so I can review the high-prio ones first sometimes). However, I don't want to limit the high-prio deck too much because there is a backlog in the low-prio deck, so a global limit will not help.
Or do not allow learning new cards in a low-prio deck while there is anything to do in the high-prio deck.

As for speed, burden calculation takes only a few seconds, but the UI stays unresponsive.

**Comment by lune-stone** [comment]
After a bit of thinking, it would probably be for the best to have the add-on be as consistent as possible with how Anki applies limits on subdecks. From my own experimenting limit calculations for new cards applies to the deck + children at each level, so it would make sense to ensure that the add-on's calculations do the same, which should already be the existing behavior.

The way the add-on's configuration is structured it's already possible to add limits to any/all levels or branches of the deck tree as desired. So the only remaining change that I see is needed would be to document how sub-deck names appear to the add-on on when altering the configuration (add a note about `::` delimited to the config.md file).

**Comment by aleksejrs** [comment]
> So the only remaining change that I see is needed would be to document how sub-deck names appear to the add-on on when altering the configuration

Maybe something could be done to help review which settings will be applied to which deck. I stumbled with
* the order
* consistency of use of `[]` and regex
* correct use of regex (I have a `+` in the name of some decks).

**Comment by lune-stone** [comment]
It would be possible to add another menu item that showed a report to that effect. Something like this perhaps:

```

rule #1 { "burdenLimit": ..., "deckNames": ["..."] }
 Applies to:
  lorem ipsum 1::Part 1::Chapter 1
  lorem ipsum 1::Part 1::Chapter 2

rule #2 { "burdenLimit": ..., "deckNames": ["..."] }
 Applies to:
  lorem ipsum 1::Part 2::Chapter 1
 Matches, but is already covered by an earlier rule:
  lorem ipsum 1::Part 1::Chapter 2 -> rule #1
  
rule #3 { "youngLimit": ..., "deckNames": "..." }
 Applies to:

not covered by any rules:
 lorem ipsum 2::Part 1::Chapter 3
 lorem ipsum 2::Part 1::Chapter 4
 
```

There are probably other ways to do this as well, but this seemed the best out of what I came up with. 

And it wouldn't hurt to add a regex sub-deck example as well.

**Comment by aleksejrs** [comment]
I like that, better than this one:

```
  lorem ipsum 1::Part 1  -> { "burdenLimit": ..., "deckNames": ["..."] }
    lorem ipsum 1::Part 1::Chapter 2  -> { "burdenLimit": ..., "deckNames": ["..."] }
      the next rule it would match is { "burdenLimit": ..., "deckNames": ["..."] }
    matches, but has limits higher than its immediate parent:
      lorem ipsum 1::Part 1::Chapter 1  -> { "burdenLimit": ..., "deckNames": ["..."] }
        the next rule it would match is { "burdenLimit": ..., "deckNames": ["..."] }
```

**Comment by aleksejrs** [comment]
```
lorem ipsum 1::Part 1::Chapter 2 -> load: 5 (of 10 of 15), young: 100 (of 200 of ∞), matched by "deckNames": ["..."] 
lorem ipsum 1::Part 1::Chapter 1 -> load: 20 (of 10 of 15), young: ∞ (of 200 of ∞), matched by "deckNames": ["..."] 
lorem ipsum 1::Part 2::Chapter 1 -> load: 5 (of 6 of 10), young: ∞ (of ∞), matched by "deckNames": ["..."] 
```

Not sure this is an acceptable use of "⊂":
```
lorem ipsum 1::Part 1::Chapter 2 -> load: 5 ⊂ 10 ⊂ 15), young: 100 ⊂ 200 ⊂ ∞, matched by "deckNames": ["..."] 
lorem ipsum 1::Part 1::Chapter 1 -> load: 20 ⊂ 10  ⊂ 15), young: ⊂ 200 ⊂ ∞, matched by "deckNames": ["..."] 
lorem ipsum 1::Part 2::Chapter 1 -> load: 5 ⊂ 6 ⊂ 10), young: ∞, matched by "deckNames": ["..."] 
```

**Comment by lune-stone** [comment]
I've updated the branch to master and added limit mapping and limit utilization report items to the menu.

Let me know if there is anything else you would like for this issue.

**Comment by aleksejrs** [comment]
If a limit is 0, Limit utilization report 

```
  File "/.local/share/Anki2/addons21/214963846burdenlimitsupport2/__init__.py", line 195, in <lambda>
    qconnect(limitUtilizationReportAction.triggered, lambda: textDialog(limitUtilizationReport()))
  File "/.local/share/Anki2/addons21/214963846burdenlimitsupport2/__init__.py", line 162, in limitUtilizationReport
    rows.append("%s%% (%d of %s)\t%s" % ("{:.2f}".format(100.0 * (load / loadLimit)), load, str(loadLimit), deckName))
ZeroDivisionError: division by zero
```

**Comment by aleksejrs** [comment]
> Not sure this is an acceptable use of "⊂":

There I meant to show the distribution of limits themselves; sorted as in the deck list, which I can approximate with this in Vim:

`:%!sort -k2 --field-separator=")"`

As for distribution of limits and burdens, maybe some kind of a graph could be generated (not in this issue).

**Comment by lune-stone** [comment]
The fix for 0 limit is on the main branch now.
