### ISSUE TITLE
Limited despite not reaching the limit percentage

### ISSUE THREAD

**Issue by GotFlojo** [lune-stone/anki-addon-limit-new-by-young#26]
I'm not sure why I am getting limited here.
Basically all of these are below 100% so shouldn't new cards remain? I'm not getting any. If I set it to the deck defaults they get removed ( I guess that is what the addon does 😅 )
I don't have any Young Limits set (default applies), just Load Limits as this is what I want to not grow.

Maybe I'm missunderstanding how this is supposed to work.

## Usage summary
>   === Young Limit ===
> 
> 
> 
> === Daily Load Limit ===
> 
> 90.36% (63.25 of 70)	Helix Keybindings
> 86.27% (116.46 of 135)	Swedish::Rivstart
> 66.25% (26.50 of 40)	Mandarin::Duolingo Chinese
> 64.06% (9.61 of 15)	Ultimate Geography
> 
> 
> === Soon Limit ===
> 
> 47.35% (232 of 490)	Helix Keybindings
> 30.00% (90 of 300)	Mandarin::Duolingo Chinese
> 20.95% (22 of 105)	Ultimate Geography

## Config
```json
{
    "limits": [
        {
            "deckNames": [
                "Swedish::Rivstart"
            ],
            "loadLimit": 135,
            "soonDays": 5
        },
        {
            "deckNames": [
                "Helix Keybindings"
            ],
            "loadLimit": 70,
            "soonDays": 7,
            "soonLimit": 490
        },
        {
            "deckNames": [
                "Ultimate Geography"
            ],
            "loadLimit": 15,
            "soonDays": 7,
            "soonLimit": 105
        },
        {
            "deckNames": [
                "Mandarin::Duolingo Chinese"
            ],
            "loadLimit": 40,
            "soonDays": 7,
            "soonLimit": 300
        }
    ],
    "rememberLastUiSettings": true,
    "showNotifications": true,
    "updateLimitsAfterSync": true,
    "updateLimitsIntervalTimeInMinutes": 15,
    "updateLimitsOnApplicationStartup": false,
    "updateLimitsOnInterval": false,
    "utilizationReport": {
        "complete": false,
        "detailLevel": "Verbose",
        "empty": false,
        "noLimit": false,
        "notStarted": false,
        "overLimit": true,
        "subDeck": true,
        "underLimit": true
    }
}
```

**Comment by lune-stone** [comment]
Based on what I'm seeing the add-on should not be limiting new cards. What is the `Daily Limits > New cards/day` limit under the deck options, and is it `Preset/This deck/Today only`? The add-on does not replace that setting so it may be the bottleneck here.

Another theory of what could be happening is that the add-on will only apply limits once per day by default. If you have been adjusting the limits then you would want to use `Tools > Limit New by Young > Recalculate today's new card limit for all decks` to force it to update. Or just wait a day.

**Comment by GotFlojo** [comment]
Let's take my swedish deck for example:
It's currently set like so: `Preset/This deck/Today`  `0/13/0` with the *Today* settings applied, meaning I don't get any cards.

If I go into the options and set it to `Deck` an hit `Save` then the _13_ new cards from the deck setting is applied (as expected). If I run `Recalculate today's new card limit for all decks` it says updated 1 Deck and I'm back to 0 new cards on the deck

**Comment by GotFlojo** [comment]
> Let's take my swedish deck for example: It's currently set like so: `Preset/This deck/Today` `0/13/0` with the _Today_ settings applied, meaning I don't get any cards.
> 
> If I go into the options and set it to `Deck` an hit `Save` then the _13_ new cards from the deck setting is applied (as expected). If I run `Recalculate today's new card limit for all decks` it says updated 1 Deck and I'm back to 0 new cards on the deck

Aahh I get it:  it uses the `Preset` for calculation, not the setting that is currently applied. If I set `Preset` to something other than 0, then I get new cards. 

Imho it should differentiate between `Preset` and `Deck`. I guess if there is a `This Deck` setting it should have precedence before the `Preset` setting. This mimics the way this option works anyway.

**Comment by lune-stone** [comment]
> Imho it should differentiate between `Preset` and `Deck`.

Agreed. It would be best to have the add-on key off of whatever value Anki uses before the add-on gets call. I'll look into what it will take to get that updated.
