### ISSUE TITLE
Intended behaviour with sub decks?

### ISSUE THREAD

**Issue by Inconsist** [lune-stone/anki-addon-limit-new-by-young#28]
# sub decks working inconsistently
### general setup:
![image](https://github.com/user-attachments/assets/ca0d476e-621c-41e8-a683-f6d6153f5cab)

### This is what the tool itself reports:
![image](https://github.com/user-attachments/assets/0239034d-30e4-46f4-bcfd-142744436b6d)
### So the way I udnerstand it is the limit for Master::TRIVIA should be: 1000-17=9983 new, but it is actually set to 1 new. The same happens for the subdecks of TRIVIA for some reason. Master:Geography should be 25 new by that logic. Also set to 1.

# Case 1: each of the trivia decks have more than 3000 cards, but when the young limit is set to 1000 I only get one new card per deck and a limit of 1 on the container deck. 
![image](https://github.com/user-attachments/assets/a963d82f-f860-4a8b-9ced-37edb7192900)
![image](https://github.com/user-attachments/assets/41846c9d-92e5-49b6-99db-43424ecaf4d1)

# Case 2: here the limits on the subdecks are actually calculated correctly, but the container deck is still locked to 1 new card.

![image](https://github.com/user-attachments/assets/c383cc01-342a-4ad7-b793-681e4b93e281)
![image](https://github.com/user-attachments/assets/a7463747-4622-4c83-8a4a-63d57b055c64)

**Comment by Inconsist** [comment]
Manually setting all of the trivia decks to 9999 new, and the recalculating the limits worked, but its concerning that they get stick once they have 1 new for that day.

The other workaround I found was to use "MASTER::TRIVIA::" in the rule, so only subdecks are calculated, and then setting the container deck to always have 9999 new manually.

**Comment by lune-stone** [comment]
Can you share what the anki "New cards/day" & "Maximum reviews/day" limits (Preset value) are for "MASTER::Geography" & "MASTER::TRIVIA"? Asking because the add-on won't replace anki limits, so if those are being hit first, then it might explain this behavior.

Another thing that might cause some confusion is that the add-on only sets the limit to a deck a single time per day, unless you use the `Tools > Limit New by Young > Recalculate today's new card limit for all decks` menu action to force it.

**Comment by Inconsist** [comment]
1. those are 9999/9999 for those, because they are the containers and they were not supposed to limit anything before either.
2. I have it setup to recalculate the limits every minute, but I also recalcualte them manually whenever I change the config

also as I said it went back to calculating correctly. I went to the parent deck, set it to preset value 9999, saved to all sub decks, then recalculated, then I got the right values, but before doing that and manually triggering recalculatiion like 6 times, the trivia decks would stay stuck at 1 new card.

**Comment by Inconsist** [comment]
I also just checked, every single subdeck now has presets where the default is 9999/9999, so I dont think thats what caused it. For example all geography subdecks have different presets, but all presets have 9999/9999 limits. So that should not be a problem.
The Trivia decks all share one trivia preset, and those didnt work correctly. But the trivia subdecks were all previously set to 1 new  but with the "This deck" option so I am not sure if it took that or the preset value.

**Comment by lune-stone** [comment]
Maybe something is up with how the add on is calculating totals then? Try running this in the debug console (open with `ctrl+shift+;`) and send back the output it gives (run with `ctrl+enter`).

```
for deckIndentifer in mw.col.decks.all_names_and_ids():

    if not deckIndentifer.name in ['MASTER::Geography', 'MASTER::TRIVIA']:
         continue

    deck = mw.col.decks.get(deckIndentifer.id)

    introduced_today = len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" introduced:1')))
    today = mw.col.sched.today
    counts = mw.col._backend.counts_for_deck_today(deckIndentifer.id)
    (newTodayDay, newTodayAmount) = deck['newToday']
    (revTodayDay, revTodayAmount) = deck['revToday']
    deck_size = len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" -is:suspended')))
    young =  len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" -is:new prop:ivl<21 -is:suspended')))

    print('name', deckIndentifer.name, 'did', deckIndentifer.id, 'ds', deck_size, 'conf', deck.get('conf'), 't', today, 'it', introduced_today, 'cn', counts.new, 'cr', counts.review, 'ntd', newTodayDay, 'nta', newTodayAmount, 'rtd', revTodayDay, 'rta', revTodayAmount, 'y', young)
```

**Comment by Inconsist** [comment]
`for deckIndentifer in mw.col.decks.all_names_and_ids():
... 
...     if not deckIndentifer.name in ['MASTER::Geography', 'MASTER::TRIVIA']:
...          continue
... 
...     deck = mw.col.decks.get(deckIndentifer.id)
... 
...     introduced_today = len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" introduced:1')))
...     today = mw.col.sched.today
...     counts = mw.col._backend.counts_for_deck_today(deckIndentifer.id)
...     (newTodayDay, newTodayAmount) = deck['newToday']
...     (revTodayDay, revTodayAmount) = deck['revToday']
...     deck_size = len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" -is:suspended')))
...     young =  len(list(mw.col.find_cards(f'deck:"{deckIndentifer.name}" -is:new prop:ivl<21 -is:suspended')))
... 
...     print('name', deckIndentifer.name, 'did', deckIndentifer.id, 'ds', deck_size, 'conf', deck.get('conf'), 't', today, 'it', introduced_today, 'cn', counts.new, 'cr', counts.review, 'ntd', newTodayDay, 'nta', newTodayAmount, 'rtd', revTodayDay, 'rta', revTodayAmount, 'y', young)
name MASTER::Geography did 1721552642322 ds 2569 conf 1 t 1102 it 2 cn 1 cr 2 ntd 1102 nta 1 rtd 1102 rta 2 y 75
name MASTER::TRIVIA did 1724818441001 ds 26014 conf 1723767796947 t 1102 it 7 cn 1 cr 0 ntd 1102 nta 1 rtd 1102 rta 0 y 17`

sorry for the weird formatting

**Comment by Inconsist** [comment]
Btw the info that your addon will not overwrite/exceed existing card limits would be nice to have, I read every piece of documentation I could find, to figure out if it handled sub decks the way i wanted, and I do not remember reading that. So it's totally possible that all trivia decks were just limited to 1 new card and I never realized that is why it is not working. 

Edit: Because it also is unintuitive. if you set a preset to 1 new card, a "today only" override of 10 new cards will work. So I ddint think of that.

**Comment by lune-stone** [comment]
The numbers from the debug are all expected. The "only set once" behavior is my current theory. If you can comment again tomorrow with how it goes I'd appreciate it.

Either I will definitely want to update the docs with this case. It's the kind of thing that would be an easy foot gun to run in to as a fresh user that just installed the add on, especially if you are adjusting the config a few times in the same day. I might also add a config option to change that behavior for auto setting as well, just to make it a bit more visible. Have to think a bit more on that.

**Comment by Inconsist** [comment]
Won't be tomorrow because I am already in ankis next day, but will keep you updated if I notice anything and if I dont. I also probably run a one in a thousand anki setup though. I keep a desktop client running 24/7 on my server which has all my addons, with it auto syncing every minute, so i can basically use addons on mobile, where I mostly do reviews throughout the day. 
The sacrafices we make for Anki ;) 
So when cards turn mature on my phone I can sync, push it to the server, and get updated limits even on mobile within two minutes. Its probably unconventional, but i see no reason why it would cause this particular issue.

**Comment by Inconsist** [comment]
The only other thing I noticed is that the update limit every n minutes doesn't actually work. I synced from my phone, after 3 cards turned mature, synced up the desktop client, I have it set to calculate every minute, and the messages tell me 3 times that 0 limits were updated, but when manually trigerring, the 1 limit changes and I get 3 new cards.
Everything else now works as expected thanks to your help.

**Comment by lune-stone** [comment]
I suspect the `updateLimitsOnInterval` is not taking effect because the limit was already set for the day. Probably the same issue as before where it only has an effect the first time, but there may also be some weirdness around when the day begins. You are the first user that I'm aware of that has a use case for having a short interval, and it likely has not had much testing in that area. The feature was originally envisioned as a alternative for users that didn't sync with ankiweb and preferred to leave anki running overnight for whatever reason (so once an hour or something).

I've pushed a change to a branch that might help. It let's you switch the default behavior of how events that automatically update limits work if the limit has already been set for the day. This may or may not be what you are looking for.

I haven't published the change to ankiweb yet, but if you are comfortable with building the add-on by hand (there is a makefile that can be used),  I'd love to hear if it's what you are looking for, or if you have something else in mind. I can also help walk you through the process if you want. Otherwise I'll probably spend a few days doing some additional testing on my side then merge the branch and publish an update.

**Comment by Inconsist** [comment]
Works perfectly now, except the addon name is differrent but that coud just be because installed from file.
I got this when anki said I had errors and I copied the debug log (dont exaclty remeber what it was called, but it was an anki popup where I could copy some log, this is it):
(I also deleted the old addon before installing the branch version)

##################################################################

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.11.8-300.fc41.x86_64-x86_64-with-glibc2.40

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.sync", line 123, in on_future_done
  File "aqt.main", line 1058, in on_collection_sync_finished
  File "aqt.hooks", line 5038, in call
  File "/home/worker/.var/app/net.ankiweb.Anki/data/Anki2/addons21/214963846/_init.py", line 39, in <lambda>
  File "/home/worker/.var/app/net.ankiweb.Anki/data/Anki2/addons21/214963846/limit.py", line 54, in update_limits
KeyError: 'updateLimitsAfterSync'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-11-16T20:25, 'None', mod]
Auto Sync ['501542723', 2023-11-20T17:14, 'None', '']
Limit New Cards Based on the Number of Young Cards ['limit-new-by-young', 0, 'None', mod]

===IDs of active AnkiWeb add-ons===
175794613 501542723

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

##################################################################

But after restarting anki it never came back witht any error messages, could be the normal, restart anki after install, but it was not there before with the stable-web version of the addon.
Otherwise, on a deck with limit 50, 2 cards turned mature on mobile, and after a while the limits were updated and I got 2 new for that deck. Thank you for the quick fix 👍

**Comment by Inconsist** [comment]
> I suspect the `updateLimitsOnInterval` is not taking effect because the limit was already set for the day. Probably the same issue as before where it only has an effect the first time, but there may also be some weirdness around when the day begins. You are the first user that I'm aware of that has a use case for having a short interval, and it likely has not had much testing in that area. The feature was originally envisioned as a alternative for users that didn't sync with ankiweb and preferred to leave anki running overnight for whatever reason (so once an hour or something).
> 
> I've pushed a change to a branch that might help. It let's you switch the default behavior of how events that automatically update limits work if the limit has already been set for the day. This may or may not be what you are looking for.
> 
> I haven't published the change to ankiweb yet, but if you are comfortable with building the add-on by hand (there is a makefile that can be used), I'd love to hear if it's what you are looking for, or if you have something else in mind. I can also help walk you through the process if you want. Otherwise I'll probably spend a few days doing some additional testing on my side then merge the branch and publish an update.

Yes that change would be what I had in mind, but it wasn't that it didn't work with small intervals, it also it didn't work when I tried 15 min or 30 min. It literally only updated when using either:

tools>limit new by young>recalculate… 
or
when a new day begins for anki(which is the same for mobile and the client)

**Comment by Inconsist** [comment]
So the way I understand it “recalculateLimitIfAlreadySet” should be set true by default, because I am pretty sure it was not the interval that was the problem.
Thinking more about it, maybe it shouldn't be a config value at all, because you already make the choice to use it indirectly when setting an interval time, so having to turn something else “true” is unintuitive. 
For example, I would in no scenario set “updateLimitsIntervalTimeInMinutes” to 15 , but then consciously turn off “recalculateLimitIfAlreadySet”. Just doesn't seem to make any sense to me whatsoever.
In the other case where you do not use an interval nothing changes any way, so again no need to have it in the config I think.
I just see the potential for people to try what I tried and forget to set it to true, which is an unnecessary pitfall.
