### ISSUE TITLE
Indicate that the add-on is working.

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#5]
During a forced recalculation, Anki's UI stays unresponsive. Now that it is not because of `mw.reset()`, there is no indication during the 3-4 seconds until the deck list is redrawn.

**Comment by lune-stone** [comment]
I think there are two changes to be made here that can both be solved with one stone. First is add a form of notifications which can probably be done with toasts, and might be nice to have a config to enable/disable. The second would be to switch to using a background thread so the UI remains responsive.  I should be able to use [this](https://addon-docs.ankiweb.net/background-ops.html) guide to do both.
