### ISSUE TITLE
Card answer side closes when recalculating

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#9]
Recalculating when the answer side is visible goes back to the question side. Not related to notifications.

**Comment by lune-stone** [comment]
This appears to be caused from using `mw.reset()`. It may be possible to poll the state of `mw` to see if you are looking at the decks, or currently reviewing cards (where we should and should not reset respectively). I'll have to do some digging on this one to find out if it is possible.

Alternatively adding another config item to disable reset would be easy to do, but the deck pages would not update numbers automatically, and would need to be navigated out and back to see the change.

**Comment by lune-stone** [comment]
Another potential is to switch from `QueryOp` to `CollectionOp` which may remove the need to use `mw.reset()`

**Comment by lune-stone** [comment]
Got some info from Anki's discord. I can use `mw.state` for this. https://github.com/ankitects/anki/blob/fa771991cabed444361de5077d6480e7471db8c5/qt/aqt/main.py#L97
